# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    # The name of the job
    name: Verify if PR is from develop branch
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{github.base_ref}} == "main"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Verify if PR is from develop branch
        shell: bash
        run: |
          if [ ! "${{ github.head_ref }}" == "develop" ]; then
            echo "Only develop branch can make pull requests to main" &&
            exit 1
          else
            exit 0
          fi
